// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customertableupdatewithdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customertableupdatewithdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201701141853339_customer table update with data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
